### ISSUE TITLE
Support latest Jupyter lab version

### ISSUE THREAD

**Issue by wexder** [osscar-org/appmode-jupyterlab#1]
Hi,
is there any plan for updating to support the newest version of jupyter lab?
![image](https://user-images.githubusercontent.com/24979302/123773069-ae0dcc80-d8cc-11eb-81e4-9cfc3bfcd6d2.jpeg)

**Comment by dou-du** [comment]
Unfortunately, the appmode server extension seems not activate with JLab 3.x. Our JLab extension does not work with JLab3.x.
